#! /usr/bin/env bash

export USER=cyrill
export HOME=/home/$USER

echo "Sourcing environment"
source /opt/ros/kinetic/setup.bash
source $HOME/ros-playground/devel/setup.bash

roslaunch deedee_tutorials main.launch
