#!/bin/sh

### BEGIN INIT INFO
# Provides:          exampledaemon
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example
# Description:       Example start-stop-daemon - Debian
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/home/cyrill/ros-playground
NAME="ros"
APPPATH="/home/cyrill/ros-playground/misc"
APPDIR="/"
APPBIN="bringup"
USER="cyrill"
GROUP="cyrill"

export PATH

# Include functions 
set -e
. /lib/lsb/init-functions

start() {
  printf "Starting '$NAME'... "
  start-stop-daemon --start \
    --chuid "$USER:$GROUP" --background \
    --make-pidfile --pidfile /var/run/$NAME.pid \
    --startas $APPPATH/$APPBIN > /home/cyrill/ros-playground/ros-daemon.log 2>&1
  printf "done\n"
}

#We need this function to ensure the whole process tree will be killed
killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

stop() {
  echo "Stopping '$NAME'... "
  printf "Stopping '$NAME'... "
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || \
  while test -d /proc/$(cat /var/run/$NAME.pid); do
    killtree $(cat /var/run/$NAME.pid) 15
    sleep 0.5
  done 
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || rm /var/run/$NAME.pid
  printf "done\n"
}

status() {
  status_of_proc -p /var/run/$NAME.pid "" $NAME && exit 0 || exit $?
}

case "$1" in
  start)
    echo "Starting '$NAME'... " >&2
    start
    ;;
  stop)
    echo "Stopping '$NAME'... " >&2
    stop
    ;;
  restart)
    echo "Restarting '$NAME'... " >&2
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
