#!/bin/sh

### BEGIN INIT INFO
# Provides:          ROS startup
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ROS middleware
# Description:       Start the ROS middleware defined in the bringup script
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin

NAME="ros"
DAEMONDIR="/home/cyrill/ros-playground/misc"
DAEMON="bringup"
USER="cyrill"
GROUP="cyrill"

export PATH

# Include functions 
set -e
. /lib/lsb/init-functions

# Start daemon
start() {
  log_daemon_msg "Starting '$NAME'... "
  start-stop-daemon --start \
    --chuid "$USER:$GROUP" --background \
    --make-pidfile --pidfile /var/run/$NAME.pid \
    --startas $DAEMONDIR/$DAEMON
  log_daemon_msg "Done"
}

# Recursive function to kill all processes started by the daemon
killtree() {
  local _pid=$1
  local _sig=${2-TERM}
  for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
    killtree ${_child} ${_sig}
  done
  kill -${_sig} ${_pid}
}

# Stop daemon
stop() {
  log_daemon_msg "Stopping '$NAME'... "
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || \
  {
    log_daemon_msg "Ending the process tree"
    killtree $(cat /var/run/$NAME.pid) 15
  }
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || rm /var/run/$NAME.pid
  log_daemon_msg "done\n"
}

status() {
  status_of_proc -p /var/run/$NAME.pid "" $NAME && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
