#!/usr/bin/env python

import rospy
from rospy import Subscriber, Publisher
from robot_control.msg import WheelSpeeds
from geometry_msgs.msg import Twist

from robot_control.movement_model_lib import DiffDrive

class MvtModelNode:
  def __init__(self):
    # Initialize the node
    rospy.init_node("movement_model")
    rospy.sleep(0.5)

    # Variables
    self.initialized = False

    # retrieve the configs and initialize the controller
    try:
      self.get_config() #L=0.6, r=0.15
      self.model = DiffDrive(self.robot_name,
                             self.model_config)
      self.initialized = True
    except KeyError as e:
      rospy.logerr("Missing config: {}".format(e))

    # Publisher/subscriber
    Subscriber("twist_cmd",
               Twist,
               self.on_twist)

    self.wheel_speeds_pub = Publisher("wheel_speeds_cmd",
                                      WheelSpeeds,
                                      queue_size=10)

    rospy.spin()

  def on_twist(self, vel):
    (u0, u1) = self.model.transform(vel.linear.x, vel.angular.z)

    msg = WheelSpeeds()
    msg.left = u1
    msg.right = u0
    self.wheel_speeds_pub.publish(msg)

  def get_config(self):
    ns = rospy.get_namespace()
    self.robot_name = ns.strip("/")
    self.model_config = rospy.get_param(ns+"movement_model")

if __name__=="__main__":
  MvtModelNode()

