#!/usr/bin/env python

import rospy
from rospy import Subscriber, Publisher
from robot_control.msg import WheelSpeeds
from geometry_msgs.msg import Twist

from robot_control.movement_model_lib import DiffDrive

class MvtModelNode:
  def __init__(self):
    rospy.init_node("movement_model")
    rospy.sleep(0.5)

    self.model = DiffDrive(L=0.6, r=0.15)

    self.wheel_speeds_sub = Subscriber("twist_cmd",
                                       Twist,
                                       self.on_twist)

    self.wheel_speeds_pub = Publisher("wheel_speeds_cmd",
                                      WheelSpeeds,
                                      queue_size=10)

    rospy.spin()

  def on_twist(self, vel):
    (u0, u1) = self.model.transform(vel.linear.x, vel.angular.z)

    msg = WheelSpeeds()
    msg.left = u1
    msg.right = u0
    self.wheel_speeds_pub.publish(msg)

if __name__=="__main__":
  MvtModelNode()
