#! /usr/bin/env bash

HOST_WS=/home/cyrill/ros-playground/ros_ws
ROS_WS=/home/serial/ros_ws

docker create \
        -p 5900:5900 \
        -p 12321:22 \
        --volume=$HOST_WS:$ROS_WS:rw \
        --name sr-dev \
        sr-dev
