deedee:
  controller:
    PID_gain: 2.
    robot_speed: .5
  observer:
    true_state:
      required: True
      timeout: 2.
  movement_model:
    L: 0.6
    r: 0.15
  motors_driver:
    serial_port: /dev/ttyACM0
    max_wheel_speed: 0.1
