FROM ubuntu:16.04
MAINTAINER Cyrill Guillemot "https://github.com/cyrillg"

# Install ROS
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
RUN apt-get update && apt-get install -y ros-kinetic-desktop-full
RUN rosdep init

# Install other utilities
RUN apt-get update && apt-get install -y \
    openssh-server \
    vim \
    tmux \
    git \
    locales \
    sudo \
    apt-utils

# Set the locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

# Configure ssh
RUN mkdir /var/run/sshd
#RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
EXPOSE 22

# Configure user
ENV USER_NAME=serial
ENV HOME=/home/$USER_NAME

RUN groupadd serial && \
    useradd --create-home --no-log-init -g serial $USER_NAME && \
    usermod -aG sudo $USER_NAME
RUN echo "$USER_NAME:$USER_NAME" | chpasswd
RUN chsh -s /bin/bash $USER_NAME

# Add files
WORKDIR $HOME
RUN rm .bashrc
COPY .bashrc .
COPY .tmux.conf .
COPY .vimrc .
ADD ros_ws ros-playground
RUN curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh > .git-prompt.bash

RUN chown serial:serial .bashrc \
                        .tmux.conf \
                        .vimrc \
                        ros-playground \
                        ros-playground/.* \
                        ros-playground/*

# Install ROS dependencies
WORKDIR $HOME/ros-playground
USER serial
RUN echo "export WS=~/" >> $HOME/.bashrc
RUN rosdep update
RUN rosdep install --rosdistro kinetic --from-paths src --ignore-src -r -y
#RUN /bin/bash --login -c "catkin_make && catkin_make install"


USER root

ENV DEBIAN_FRONTEND noninteractive

RUN sed -i 's#http://archive.ubuntu.com/#http://tw.archive.ubuntu.com/#' /etc/apt/sources.list

# built-in packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common curl \
    && sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /' >> /etc/apt/sources.list.d/arc-theme.list" \
    && curl -SL http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key | apt-key add - \
    && add-apt-repository ppa:fcwu-tw/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends --allow-unauthenticated \
        supervisor \
        openssh-server pwgen sudo vim-tiny \
        net-tools \
        lxde x11vnc xvfb \
        gtk2-engines-murrine ttf-ubuntu-font-family \
        libreoffice firefox \
        fonts-wqy-microhei \
        language-pack-zh-hant language-pack-gnome-zh-hant firefox-locale-zh-hant libreoffice-l10n-zh-tw \
        nginx \
        python-pip python-dev build-essential \
        mesa-utils libgl1-mesa-dri \
        gnome-themes-standard gtk2-engines-pixbuf gtk2-engines-murrine pinta arc-theme \
        dbus-x11 x11-utils \
    && apt-get autoclean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*


# tini for subreap
ENV TINI_VERSION v0.9.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /bin/tini
RUN chmod +x /bin/tini

ADD image /
RUN pip install setuptools wheel && pip install -r /usr/lib/web/requirements.txt

EXPOSE 80
WORKDIR /root
ENV HOME=/home/serial \
    SHELL=/bin/bash
ENTRYPOINT ["/startup.sh"]
