#! /usr/bin/env bash

# This script requires the WS environment variable to be set
# For convenience, it can be done in the bashrc

echo "Sourcing environment"
source /opt/ros/kinetic/setup.bash
source $WS/ros_ws/devel/setup.bash

roslaunch deedee_tutorials main.launch

