#!/usr/bin/env bash

echo -n "Are you sure you want to delete the sr-dev image? (y/n) "
read res

if [[ "$res" == "y" ]]; then
    docker rmi sr-dev
    echo "sr-dev image deleted"
else
    echo "Cancelled"
fi

