#!/usr/bin/env bash

if [[ -f "Dockerfile" ]]; then
    docker build . -t sr-dev
else
    echo "This directory does not contain a Dockerfile. Please:"
    echo "  - go to the root of the image definition"
    echo "  - run this command again"
    exit 3
fi

ROS_WS=/home/serial/ros_ws
HOST_WS_DEFAULT=`pwd`
HOST_WS="${1-$HOST_WS_DEFAULT}"

if [[ -f "$HOST_WS/.catkin_workspace" ]]; then
    echo "Building image..."
    docker build . -t sr-dev
else
    echo "The current directory is not a catkin workspace."
    echo "Please verify the path"
    exit 2
fi

img_name=`docker images --filter=reference=sr-dev --format "{{.Repository}}"`
echo $img_name
echo $ROS_WS
echo $HOST_WS
if [[ ! -z "$img_name" ]]; then
    echo "Creating instance..."
    docker create \
            -p 5900:5900 \
            -p 12321:22 \
            --volume=$HOST_WS:$ROS_WS:rw \
            --name sr-dev \
            sr-dev
else
    echo "Something went wrong. The base image did not build successfully"
    exit 1
fi

